///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VodafonePOC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddSchedule recording.
    /// </summary>
    [TestModule("429990a3-1458-4dfd-990c-16900f0aa5c1", ModuleType.Recording, 1)]
    public partial class AddSchedule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VodafonePOCRepository repository.
        /// </summary>
        public static VodafonePOCRepository repo = VodafonePOCRepository.Instance;

        static AddSchedule instance = new AddSchedule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddSchedule()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddSchedule Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddDay' at 172;14.", repo.ApplicationUnderTest.AddDayInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AddDay.Click("172;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NgScope' at 60;291.", repo.ApplicationUnderTest.NgScopeInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.NgScope.Click("60;291");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NgScope' at 340;256.", repo.ApplicationUnderTest.NgScopeInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.NgScope.Click("340;256");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'number:0' on item 'ApplicationUnderTest.AddTimeHours'.", repo.ApplicationUnderTest.AddTimeHoursInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.AddTimeHours.Element.SetAttributeValue("TagValue", "number:0");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown.Client' at 16;7.", repo.Dropdown.ClientInfo, new RecordItemIndex(4));
            repo.Dropdown.Client.Click("16;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddAction' at 20;25.", repo.ApplicationUnderTest.AddActionInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AddAction.Click("20;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Form' at 544;361.", repo.ApplicationUnderTest.FormInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Form.Click("544;361");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 45;16.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Submit.Click("45;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
