///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VodafonePOC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ExceptionList_Click recording.
    /// </summary>
    [TestModule("38b62c9c-4c1c-4403-80ba-c9bdcba60a28", ModuleType.Recording, 1)]
    public partial class ExceptionList_Click : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VodafonePOCRepository repository.
        /// </summary>
        public static VodafonePOCRepository repo = VodafonePOCRepository.Instance;

        static ExceptionList_Click instance = new ExceptionList_Click();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ExceptionList_Click()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ExceptionList_Click Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ContentPage.ExceptionLists' at 56;7.", repo.ApplicationUnderTest.ContentPage.ExceptionListsInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ContentPage.ExceptionLists.Click("56;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ContentPage.ChooseDefaultForThisDomain' at 85;37.", repo.ApplicationUnderTest.ContentPage.ChooseDefaultForThisDomainInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ContentPage.ChooseDefaultForThisDomain.Click("85;37");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.EXCEPTIONS' at 512;15.", repo.ApplicationUnderTest.EXCEPTIONSInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.EXCEPTIONS.Click("512;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NgScope' at 101;107.", repo.ApplicationUnderTest.NgScopeInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.NgScope.Click("101;107");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 42;14.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Submit.Click("42;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
