///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VodafonePOC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VodafonePOCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
    public partial class VodafonePOCRepository : RepoGenBaseFolder
    {
        static VodafonePOCRepository instance = new VodafonePOCRepository();
        VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder _microsoftedge;
        VodafonePOCRepositoryFolders.DropdownAppFolder _dropdown;
        VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder _characterencodingrstudiosupport;

        /// <summary>
        /// Gets the singleton class instance representing the VodafonePOCRepository element repository.
        /// </summary>
        [RepositoryFolder("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
        public static VodafonePOCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VodafonePOCRepository() 
            : base("VodafonePOCRepository", "/", null, 0, false, "146bcdc9-cac8-4e11-8b44-873bb922bd05", ".\\RepositoryImages\\VodafonePOCRepository146bcdc9.rximgres")
        {
            _applicationundertest = new VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _microsoftedge = new VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder(this);
            _dropdown = new VodafonePOCRepositoryFolders.DropdownAppFolder(this);
            _characterencodingrstudiosupport = new VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b9a60ef8-a539-4715-a337-85a448c239ae")]
        public virtual VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The MicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
        public virtual VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder MicrosoftEdge
        {
            get { return _microsoftedge; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
        public virtual VodafonePOCRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The CharacterEncodingRStudioSupport folder.
        /// </summary>
        [RepositoryFolder("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
        public virtual VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder CharacterEncodingRStudioSupport
        {
            get { return _characterencodingrstudiosupport; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VodafonePOCRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9a60ef8-a539-4715-a337-85a448c239ae")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            VodafonePOCRepositoryFolders.ContentPageFolder _contentpage;
            RepoItemInfo _fullwidthngscopeInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _scheduleInfo;
            RepoItemInfo _pickyouralarmsettingsInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _accountInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _account1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='ext-735-opco.caas.edgevis.io:9443']", parentFolder, 30000, null, false, "b9a60ef8-a539-4715-a337-85a448c239ae", "")
            {
                _contentpage = new VodafonePOCRepositoryFolders.ContentPageFolder(this);
                _fullwidthngscopeInfo = new RepoItemInfo(this, "FullWidthNgScope", ".//body[#'top']/header", 30000, null, "23e12b43-add1-41ac-ba15-4286b8342e8c");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b");
                _scheduleInfo = new RepoItemInfo(this, "SCHEDULE", ".//form[#'form']/div//select[@name='SCHEDULE']", 30000, null, "58eaa606-0c7b-4cf1-a77b-6e8179645aac");
                _pickyouralarmsettingsInfo = new RepoItemInfo(this, "PickYourAlarmSettings", ".//form[#'form']/h1[@innertext='Pick your alarm settings']", 30000, null, "59e41956-c6ea-4a0c-8f1f-c60b14bd26c8");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "653dc6ae-5054-4c3b-8dd7-56323e2d08f2");
                _accountInfo = new RepoItemInfo(this, "Account", ".//div[#'userPanel']/span[3]", 30000, null, "c09551df-3b95-40e6-aa88-dd8bae88aec2");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "b4031387-8833-4efa-ade4-97b0c7f4b3ad");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'userPanel']//a[@innertext='Logout']", 30000, null, "e46edd80-b215-4542-bb5a-fa434cc8c32f");
                _account1Info = new RepoItemInfo(this, "Account1", ".//div[#'userPanel']/span[2]", 30000, null, "a2b9049e-c483-401a-ba9f-76a84767f0d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9a60ef8-a539-4715-a337-85a448c239ae")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9a60ef8-a539-4715-a337-85a448c239ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FullWidthNgScope item.
            /// </summary>
            [RepositoryItem("23e12b43-add1-41ac-ba15-4286b8342e8c")]
            public virtual Ranorex.HeaderTag FullWidthNgScope
            {
                get
                {
                    return _fullwidthngscopeInfo.CreateAdapter<Ranorex.HeaderTag>(true);
                }
            }

            /// <summary>
            /// The FullWidthNgScope item info.
            /// </summary>
            [RepositoryItemInfo("23e12b43-add1-41ac-ba15-4286b8342e8c")]
            public virtual RepoItemInfo FullWidthNgScopeInfo
            {
                get
                {
                    return _fullwidthngscopeInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The SCHEDULE item.
            /// </summary>
            [RepositoryItem("58eaa606-0c7b-4cf1-a77b-6e8179645aac")]
            public virtual Ranorex.SelectTag SCHEDULE
            {
                get
                {
                    return _scheduleInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SCHEDULE item info.
            /// </summary>
            [RepositoryItemInfo("58eaa606-0c7b-4cf1-a77b-6e8179645aac")]
            public virtual RepoItemInfo SCHEDULEInfo
            {
                get
                {
                    return _scheduleInfo;
                }
            }

            /// <summary>
            /// The PickYourAlarmSettings item.
            /// </summary>
            [RepositoryItem("59e41956-c6ea-4a0c-8f1f-c60b14bd26c8")]
            public virtual Ranorex.H1Tag PickYourAlarmSettings
            {
                get
                {
                    return _pickyouralarmsettingsInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The PickYourAlarmSettings item info.
            /// </summary>
            [RepositoryItemInfo("59e41956-c6ea-4a0c-8f1f-c60b14bd26c8")]
            public virtual RepoItemInfo PickYourAlarmSettingsInfo
            {
                get
                {
                    return _pickyouralarmsettingsInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("653dc6ae-5054-4c3b-8dd7-56323e2d08f2")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("653dc6ae-5054-4c3b-8dd7-56323e2d08f2")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Account item.
            /// </summary>
            [RepositoryItem("c09551df-3b95-40e6-aa88-dd8bae88aec2")]
            public virtual Ranorex.SpanTag Account
            {
                get
                {
                    return _accountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account item info.
            /// </summary>
            [RepositoryItemInfo("c09551df-3b95-40e6-aa88-dd8bae88aec2")]
            public virtual RepoItemInfo AccountInfo
            {
                get
                {
                    return _accountInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("b4031387-8833-4efa-ade4-97b0c7f4b3ad")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("b4031387-8833-4efa-ade4-97b0c7f4b3ad")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("e46edd80-b215-4542-bb5a-fa434cc8c32f")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("e46edd80-b215-4542-bb5a-fa434cc8c32f")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Account1 item.
            /// </summary>
            [RepositoryItem("a2b9049e-c483-401a-ba9f-76a84767f0d6")]
            public virtual Ranorex.SpanTag Account1
            {
                get
                {
                    return _account1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account1 item info.
            /// </summary>
            [RepositoryItemInfo("a2b9049e-c483-401a-ba9f-76a84767f0d6")]
            public virtual RepoItemInfo Account1Info
            {
                get
                {
                    return _account1Info;
                }
            }

            /// <summary>
            /// The ContentPage folder.
            /// </summary>
            [RepositoryFolder("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual VodafonePOCRepositoryFolders.ContentPageFolder ContentPage
            {
                get { return _contentpage; }
            }
        }

        /// <summary>
        /// The ContentPageFolder folder.
        /// </summary>
        [RepositoryFolder("373057e6-3382-4e46-815b-737e7abdbb6b")]
        public partial class ContentPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _choosedefaultforthisdomainInfo;
            RepoItemInfo _testInfo;
            RepoItemInfo _encodersettingsInfo;

            /// <summary>
            /// Creates a new ContentPage  folder.
            /// </summary>
            public ContentPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentPage", ".//section[#'float']/div/div/div", parentFolder, 30000, null, false, "373057e6-3382-4e46-815b-737e7abdbb6b", "")
            {
                _choosedefaultforthisdomainInfo = new RepoItemInfo(this, "ChooseDefaultForThisDomain", "aside/ul/?/?/a[@innertext>'Choose default for this d']", 30000, null, "3aafab49-fb6a-4ed7-8831-7fcb38ebc523");
                _testInfo = new RepoItemInfo(this, "Test", "ul[1]/li[1]/a[@innertext='Test ']", 30000, null, "83065ac3-620b-48c5-a7e0-909a68083265");
                _encodersettingsInfo = new RepoItemInfo(this, "EncoderSettings", "ul[2]/?/?/a[@innertext='Encoder settings']", 30000, null, "078447a5-ed66-46f8-aa3e-51d4bde59158");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChooseDefaultForThisDomain item.
            /// </summary>
            [RepositoryItem("3aafab49-fb6a-4ed7-8831-7fcb38ebc523")]
            public virtual Ranorex.ATag ChooseDefaultForThisDomain
            {
                get
                {
                    return _choosedefaultforthisdomainInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ChooseDefaultForThisDomain item info.
            /// </summary>
            [RepositoryItemInfo("3aafab49-fb6a-4ed7-8831-7fcb38ebc523")]
            public virtual RepoItemInfo ChooseDefaultForThisDomainInfo
            {
                get
                {
                    return _choosedefaultforthisdomainInfo;
                }
            }

            /// <summary>
            /// The Test item.
            /// </summary>
            [RepositoryItem("83065ac3-620b-48c5-a7e0-909a68083265")]
            public virtual Ranorex.ATag Test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Test item info.
            /// </summary>
            [RepositoryItemInfo("83065ac3-620b-48c5-a7e0-909a68083265")]
            public virtual RepoItemInfo TestInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The EncoderSettings item.
            /// </summary>
            [RepositoryItem("078447a5-ed66-46f8-aa3e-51d4bde59158")]
            public virtual Ranorex.ATag EncoderSettings
            {
                get
                {
                    return _encodersettingsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EncoderSettings item info.
            /// </summary>
            [RepositoryItemInfo("078447a5-ed66-46f8-aa3e-51d4bde59158")]
            public virtual RepoItemInfo EncoderSettingsInfo
            {
                get
                {
                    return _encodersettingsInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
        public partial class MicrosoftEdgeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchorenterwebaddressInfo;
            RepoItemInfo _sometextInfo;

            /// <summary>
            /// Creates a new MicrosoftEdge  folder.
            /// </summary>
            public MicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftEdge", "/winapp[@packagename='Microsoft.MicrosoftEdge']", parentFolder, 30000, null, true, "763b2766-dcca-4ff9-9878-dc48c2a3f4fe", "")
            {
                _searchorenterwebaddressInfo = new RepoItemInfo(this, "SearchOrEnterWebAddress", "?/?/text[@name>'Search or enter web addre']", 30000, null, "30c0962c-9ff4-48d4-b562-78ecf6f7d11b");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "list[@automationid='TabsList']//button[@automationid='AllInputCloseButton']/text[@name='']", 30000, null, "4e49b5cf-1978-4d31-88e3-601ad15bb00d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchOrEnterWebAddress item.
            /// </summary>
            [RepositoryItem("30c0962c-9ff4-48d4-b562-78ecf6f7d11b")]
            public virtual Ranorex.Text SearchOrEnterWebAddress
            {
                get
                {
                    return _searchorenterwebaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SearchOrEnterWebAddress item info.
            /// </summary>
            [RepositoryItemInfo("30c0962c-9ff4-48d4-b562-78ecf6f7d11b")]
            public virtual RepoItemInfo SearchOrEnterWebAddressInfo
            {
                get
                {
                    return _searchorenterwebaddressInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("4e49b5cf-1978-4d31-88e3-601ad15bb00d")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("4e49b5cf-1978-4d31-88e3-601ad15bb00d")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "de3b3b23-69e2-4e5a-92fe-7fd1894fa041", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "listitem", 30000, null, "a333b0d6-92ea-41fa-9477-0e56def63af8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("a333b0d6-92ea-41fa-9477-0e56def63af8")]
            public virtual Ranorex.ListItem Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("a333b0d6-92ea-41fa-9477-0e56def63af8")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }
        }

        /// <summary>
        /// The CharacterEncodingRStudioSupportAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
        public partial class CharacterEncodingRStudioSupportAppFolder : RepoGenBaseFolder
        {
            VodafonePOCRepositoryFolders.SomeMainTagFolder _somemaintag;
            RepoItemInfo _communityenabledInfo;

            /// <summary>
            /// Creates a new CharacterEncodingRStudioSupport  folder.
            /// </summary>
            public CharacterEncodingRStudioSupportAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CharacterEncodingRStudioSupport", "/dom[@domain='support.rstudio.com']", parentFolder, 30000, null, false, "3ff4ab92-369d-4ee9-a944-6c8be07d020c", "")
            {
                _somemaintag = new VodafonePOCRepositoryFolders.SomeMainTagFolder(this);
                _communityenabledInfo = new RepoItemInfo(this, "CommunityEnabled", "body", 30000, null, "158004ef-e852-4bbc-a50f-d8d82abb8705");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CommunityEnabled item.
            /// </summary>
            [RepositoryItem("158004ef-e852-4bbc-a50f-d8d82abb8705")]
            public virtual Ranorex.BodyTag CommunityEnabled
            {
                get
                {
                    return _communityenabledInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The CommunityEnabled item info.
            /// </summary>
            [RepositoryItemInfo("158004ef-e852-4bbc-a50f-d8d82abb8705")]
            public virtual RepoItemInfo CommunityEnabledInfo
            {
                get
                {
                    return _communityenabledInfo;
                }
            }

            /// <summary>
            /// The SomeMainTag folder.
            /// </summary>
            [RepositoryFolder("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual VodafonePOCRepositoryFolders.SomeMainTagFolder SomeMainTag
            {
                get { return _somemaintag; }
            }
        }

        /// <summary>
        /// The SomeMainTagFolder folder.
        /// </summary>
        [RepositoryFolder("22185695-afd3-4091-874d-ae9fa0d5ca60")]
        public partial class SomeMainTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ifyoudontsetadefaultencodingfileInfo;
            RepoItemInfo _ifyoufrequentlyusethecharactersetInfo;
            RepoItemInfo _articlebodyInfo;

            /// <summary>
            /// Creates a new SomeMainTag  folder.
            /// </summary>
            public SomeMainTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeMainTag", "?/?/main", parentFolder, 30000, null, false, "22185695-afd3-4091-874d-ae9fa0d5ca60", "")
            {
                _ifyoudontsetadefaultencodingfileInfo = new RepoItemInfo(this, "IfYouDontSetADefaultEncodingFile", "?/?/article/?/?/p[@innertext>'If you don''t set a default']", 30000, null, "2819a39d-14d5-4e9c-9e7b-8f810d0a9a26");
                _ifyoufrequentlyusethecharactersetInfo = new RepoItemInfo(this, "IfYouFrequentlyUseTheCharacterSet", "?/?/article/?/?/p[@innertext>'If you frequently use the']", 30000, null, "adbd7a80-cb69-4357-9c1f-3c3101c12392");
                _articlebodyInfo = new RepoItemInfo(this, "ArticleBody", "?/?/article/div[1]", 30000, null, "2d9a0b5c-bac9-44e0-ae84-c2becd94695a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual Ranorex.MainTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MainTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IfYouDontSetADefaultEncodingFile item.
            /// </summary>
            [RepositoryItem("2819a39d-14d5-4e9c-9e7b-8f810d0a9a26")]
            public virtual Ranorex.PTag IfYouDontSetADefaultEncodingFile
            {
                get
                {
                    return _ifyoudontsetadefaultencodingfileInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IfYouDontSetADefaultEncodingFile item info.
            /// </summary>
            [RepositoryItemInfo("2819a39d-14d5-4e9c-9e7b-8f810d0a9a26")]
            public virtual RepoItemInfo IfYouDontSetADefaultEncodingFileInfo
            {
                get
                {
                    return _ifyoudontsetadefaultencodingfileInfo;
                }
            }

            /// <summary>
            /// The IfYouFrequentlyUseTheCharacterSet item.
            /// </summary>
            [RepositoryItem("adbd7a80-cb69-4357-9c1f-3c3101c12392")]
            public virtual Ranorex.PTag IfYouFrequentlyUseTheCharacterSet
            {
                get
                {
                    return _ifyoufrequentlyusethecharactersetInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IfYouFrequentlyUseTheCharacterSet item info.
            /// </summary>
            [RepositoryItemInfo("adbd7a80-cb69-4357-9c1f-3c3101c12392")]
            public virtual RepoItemInfo IfYouFrequentlyUseTheCharacterSetInfo
            {
                get
                {
                    return _ifyoufrequentlyusethecharactersetInfo;
                }
            }

            /// <summary>
            /// The ArticleBody item.
            /// </summary>
            [RepositoryItem("2d9a0b5c-bac9-44e0-ae84-c2becd94695a")]
            public virtual Ranorex.DivTag ArticleBody
            {
                get
                {
                    return _articlebodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArticleBody item info.
            /// </summary>
            [RepositoryItemInfo("2d9a0b5c-bac9-44e0-ae84-c2becd94695a")]
            public virtual RepoItemInfo ArticleBodyInfo
            {
                get
                {
                    return _articlebodyInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
