///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VodafonePOC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VodafonePOCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
    public partial class VodafonePOCRepository : RepoGenBaseFolder
    {
        static VodafonePOCRepository instance = new VodafonePOCRepository();
        VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder _microsoftedge;
        VodafonePOCRepositoryFolders.DropdownAppFolder _dropdown;
        VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder _characterencodingrstudiosupport;
        VodafonePOCRepositoryFolders.Ranorex93GoogleSearchAppFolder _ranorex93googlesearch;
        VodafonePOCRepositoryFolders.MyhrtoolkitHRSoftwareAsAServiceAppFolder _myhrtoolkithrsoftwareasaservice;
        VodafonePOCRepositoryFolders.GTBoardAgileBoardJiraAppFolder _gtboardagileboardjira;
        VodafonePOCRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the VodafonePOCRepository element repository.
        /// </summary>
        [RepositoryFolder("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
        public static VodafonePOCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VodafonePOCRepository() 
            : base("VodafonePOCRepository", "/", null, 0, false, "146bcdc9-cac8-4e11-8b44-873bb922bd05", ".\\RepositoryImages\\VodafonePOCRepository146bcdc9.rximgres")
        {
            _applicationundertest = new VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _microsoftedge = new VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder(this);
            _dropdown = new VodafonePOCRepositoryFolders.DropdownAppFolder(this);
            _characterencodingrstudiosupport = new VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder(this);
            _ranorex93googlesearch = new VodafonePOCRepositoryFolders.Ranorex93GoogleSearchAppFolder(this);
            _myhrtoolkithrsoftwareasaservice = new VodafonePOCRepositoryFolders.MyhrtoolkitHRSoftwareAsAServiceAppFolder(this);
            _gtboardagileboardjira = new VodafonePOCRepositoryFolders.GTBoardAgileBoardJiraAppFolder(this);
            _explorer = new VodafonePOCRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

        string _save = "";

        /// <summary>
        /// Gets or sets the value of variable save.
        /// </summary>
        [TestVariable("f2e6ba2f-cab0-402d-995f-edb030525bd6")]
        public string save
        {
            get { return _save; }
            set { _save = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("146bcdc9-cac8-4e11-8b44-873bb922bd05")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b9a60ef8-a539-4715-a337-85a448c239ae")]
        public virtual VodafonePOCRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The MicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
        public virtual VodafonePOCRepositoryFolders.MicrosoftEdgeAppFolder MicrosoftEdge
        {
            get { return _microsoftedge; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
        public virtual VodafonePOCRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The CharacterEncodingRStudioSupport folder.
        /// </summary>
        [RepositoryFolder("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
        public virtual VodafonePOCRepositoryFolders.CharacterEncodingRStudioSupportAppFolder CharacterEncodingRStudioSupport
        {
            get { return _characterencodingrstudiosupport; }
        }

        /// <summary>
        /// The Ranorex93GoogleSearch folder.
        /// </summary>
        [RepositoryFolder("739c31f1-4f9e-425e-b95d-733894c2348f")]
        public virtual VodafonePOCRepositoryFolders.Ranorex93GoogleSearchAppFolder Ranorex93GoogleSearch
        {
            get { return _ranorex93googlesearch; }
        }

        /// <summary>
        /// The MyhrtoolkitHRSoftwareAsAService folder.
        /// </summary>
        [RepositoryFolder("9f1caf70-70ae-4b26-86cb-dfa2261cdeec")]
        public virtual VodafonePOCRepositoryFolders.MyhrtoolkitHRSoftwareAsAServiceAppFolder MyhrtoolkitHRSoftwareAsAService
        {
            get { return _myhrtoolkithrsoftwareasaservice; }
        }

        /// <summary>
        /// The GTBoardAgileBoardJira folder.
        /// </summary>
        [RepositoryFolder("654275ce-97aa-416e-803a-bc6f7cbb9ab5")]
        public virtual VodafonePOCRepositoryFolders.GTBoardAgileBoardJiraAppFolder GTBoardAgileBoardJira
        {
            get { return _gtboardagileboardjira; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("71bcaed3-06c6-4394-8cef-a16b6b1b952d")]
        public virtual VodafonePOCRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VodafonePOCRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9a60ef8-a539-4715-a337-85a448c239ae")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            VodafonePOCRepositoryFolders.ContentPageFolder _contentpage;
            RepoItemInfo _fullwidthngscopeInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _scheduleInfo;
            RepoItemInfo _pickyouralarmsettingsInfo;
            RepoItemInfo _accountInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _testInfo;
            RepoItemInfo _findoutmoreaboutalarmschedulingInfo;
            RepoItemInfo _thursdayworkinghoursInfo;
            RepoItemInfo _adddayInfo;
            RepoItemInfo _ngscopeInfo;
            RepoItemInfo _addtimehoursInfo;
            RepoItemInfo _addactionInfo;
            RepoItemInfo _formInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _sometdtagInfo;
            RepoItemInfo _deletescheduleInfo;
            RepoItemInfo _bodytagtopInfo;
            RepoItemInfo _addday1Info;
            RepoItemInfo _sometdtag1Info;
            RepoItemInfo _confirmInfo;
            RepoItemInfo _alarmschedulingInfo;
            RepoItemInfo _exceptionlistInfo;
            RepoItemInfo _test1Info;
            RepoItemInfo _adddateInfo;
            RepoItemInfo _atagaddInfo;
            RepoItemInfo _exceptionsInfo;
            DefaultForThisDomainInfoClass _defaultforthisdomainInfo;
            HttpsExt735OpcoCaasEdgevisIo944InfoClass _httpsext735opcocaasedgevisio944Info;
            RepoItemInfo _defaultforthisdomain1Info;
            RepoItemInfo _selectanexceptionlistInfo;
            RepoItemInfo _containerngscopeInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _test11Info;
            RepoItemInfo _findoutmoreaboutalarmscheduling1Info;
            RepoItemInfo _exceptionlistsInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='ext-735-opco.caas.edgevis.io:9443']", parentFolder, 30000, null, false, "b9a60ef8-a539-4715-a337-85a448c239ae", "")
            {
                _contentpage = new VodafonePOCRepositoryFolders.ContentPageFolder(this);
                _fullwidthngscopeInfo = new RepoItemInfo(this, "FullWidthNgScope", ".//body[#'top']/header", 30000, null, "23e12b43-add1-41ac-ba15-4286b8342e8c");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b");
                _scheduleInfo = new RepoItemInfo(this, "SCHEDULE", ".//form[#'form']/div//select[@name='SCHEDULE']", 30000, null, "58eaa606-0c7b-4cf1-a77b-6e8179645aac");
                _pickyouralarmsettingsInfo = new RepoItemInfo(this, "PickYourAlarmSettings", ".//form[#'form']/h1[@innertext='Pick your alarm settings']", 30000, null, "59e41956-c6ea-4a0c-8f1f-c60b14bd26c8");
                _accountInfo = new RepoItemInfo(this, "Account", ".//div[#'userPanel']/span[3]", 30000, null, "c09551df-3b95-40e6-aa88-dd8bae88aec2");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "b4031387-8833-4efa-ade4-97b0c7f4b3ad");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'userPanel']//a[@innertext='Logout']", 30000, null, "e46edd80-b215-4542-bb5a-fa434cc8c32f");
                _testInfo = new RepoItemInfo(this, "Test", ".//section[#'float']//article/ul/li[14]//span[@innertext='test ']", 30000, null, "a1a2654c-6152-49ff-9e74-ce7b54aebf8b");
                _findoutmoreaboutalarmschedulingInfo = new RepoItemInfo(this, "FindOutMoreAboutAlarmScheduling", ".//section[#'float']//article/p[@innertext>'This section allows you to']/a[@innertext>'Find out more about alarm']", 30000, null, "bc16c320-b69e-4103-85e9-5476fb896510");
                _thursdayworkinghoursInfo = new RepoItemInfo(this, "ThursdayWorkingHours", ".//section[#'float']//article/ul/li[1]//span[@innertext='Thursday Working hours ']", 30000, null, "bf3cc242-118b-4782-a062-cbcf0f0d2894");
                _adddayInfo = new RepoItemInfo(this, "AddDay", ".//select[#'addDay']", 30000, null, "3ab2d50e-ee87-48fb-8264-e872e0a35672");
                _ngscopeInfo = new RepoItemInfo(this, "NgScope", ".//form[#'form']/div", 30000, null, "77f69edd-8288-4cb8-b705-41129eb5713f");
                _addtimehoursInfo = new RepoItemInfo(this, "AddTimeHours", ".//select[#'addTimeHours']", 30000, null, "20178f26-3265-4566-9a59-7c1d1f53125f");
                _addactionInfo = new RepoItemInfo(this, "AddAction", ".//select[#'addAction']", 30000, null, "ffae465f-840e-49a9-b48d-6ff1d0a1e7eb");
                _formInfo = new RepoItemInfo(this, "Form", ".//form[#'form']", 30000, null, "1316e814-89ac-484e-85d1-ec38c3c1eeda");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//form[#'form']/div/table[1]/tbody/tr[3]/td[4]/a[@innertext='Delete']", 30000, null, "b489380f-8232-408c-aa99-67657f2983dd");
                _sometdtagInfo = new RepoItemInfo(this, "SomeTdTag", ".//form[#'form']/div/table[1]/tbody/tr/td[4]", 30000, null, "7c6ec7aa-b898-49c5-8b17-8c4c455fb9bf");
                _deletescheduleInfo = new RepoItemInfo(this, "DeleteSchedule", ".//form[#'form']//a[@innertext='Delete schedule']", 30000, null, "9b858aea-7460-4efb-bf08-80249436dbfc");
                _bodytagtopInfo = new RepoItemInfo(this, "BodyTagTop", ".//body[#'top']", 30000, null, "e2662629-bfc7-4dec-ac3a-2ee8f34794bd");
                _addday1Info = new RepoItemInfo(this, "AddDay1", ".//section[#'float']//form/div/table[2]/?/?/tr/td[1]/select[@id='addDay']", 30000, null, "be6aa740-6b69-4248-8617-a398475fba47");
                _sometdtag1Info = new RepoItemInfo(this, "SomeTdTag1", ".//section[#'float']//form/div/table[2]/?/?/tr/td[1]", 30000, null, "63728c1c-ee87-426e-bac4-63d36c1d8c26");
                _confirmInfo = new RepoItemInfo(this, "Confirm", ".//div[#'loading']/?/?/a[@innertext='Confirm']", 30000, null, "72ba7444-4873-47bd-97cb-4187b3268126");
                _alarmschedulingInfo = new RepoItemInfo(this, "AlarmScheduling", ".//section[#'float']//article/ul/li[1]//span[@innertext='Alarm scheduling']", 30000, null, "2f92af02-1ee3-428b-9cf4-6891c1f47c8b");
                _exceptionlistInfo = new RepoItemInfo(this, "ExceptionList", ".//section[#'float']//article/ul/li[1]//span[@innertext='Exception list ']", 30000, null, "5e11aa18-727d-46f7-b1ac-e84a530232a6");
                _test1Info = new RepoItemInfo(this, "Test1", ".//section[#'float']//article/ul/li[4]//span[@innertext='Test 1 ']", 30000, null, "05d0a20b-9ece-4d13-b173-692746dfd958");
                _adddateInfo = new RepoItemInfo(this, "AddDate", ".//input[#'addDate']", 30000, null, "5b3dcac7-6c22-444e-8a84-47d3e3c7ef8b");
                _atagaddInfo = new RepoItemInfo(this, "ATagAdd", ".//form[#'form']/div/table[2]//a[@innertext='Add']", 30000, null, "8616b60b-5ac2-40fb-9df6-5c4c25fb926a");
                _exceptionsInfo = new RepoItemInfo(this, "EXCEPTIONS", ".//form[#'form']/div//select[@name='EXCEPTIONS']", 30000, null, "758df2dc-ef7e-40b2-aadc-d2a7a22f220a");
                _defaultforthisdomainInfo = new DefaultForThisDomainInfoClass(this);
                _httpsext735opcocaasedgevisio944Info = new HttpsExt735OpcoCaasEdgevisIo944InfoClass(this);
                _defaultforthisdomain1Info = new RepoItemInfo(this, "DefaultForThisDomain1", ".//section[#'float']//article/ul/li[10]//span[@innertext='Weekend ']", 30000, null, "04b583ba-4c91-41ae-8c11-8107ee34b9a8");
                _selectanexceptionlistInfo = new RepoItemInfo(this, "SelectAnExceptionList", ".//form[#'form']/?/?/h2[@innertext='Select an exception list']", 30000, null, "4ff8a0f0-2bca-4c15-8dc8-8ec295dc0774");
                _containerngscopeInfo = new RepoItemInfo(this, "ContainerNgScope", ".//section[#'float']/?/?/div", 30000, null, "e63a6a85-b91a-44c0-ba73-d86629360a66");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "c6e54d69-a969-4aca-87ca-3a86f823f66c");
                _test11Info = new RepoItemInfo(this, "Test11", ".//section[#'float']//article/ul/li[6]//span[@innertext='Test 1 ']", 30000, null, "6643b1d9-57e4-44c1-a983-369b97ed1df7");
                _findoutmoreaboutalarmscheduling1Info = new RepoItemInfo(this, "FindOutMoreAboutAlarmScheduling1", ".//section[#'float']//article/p[@innertext>'Exception lists allow you']/a[@innertext>'Find out more about alarm']", 30000, null, "49e333cc-2606-43b1-9b28-e01d0d461c3f");
                _exceptionlistsInfo = new RepoItemInfo(this, "ExceptionLists", ".//form[#'form']/?/?/strong[@innertext='Exception lists']", 30000, null, "15b0f15b-bd48-486c-9933-d92798e40b94");
            }

            /// <summary>
            /// The DefaultForThisDomainInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("d01638b7-aad6-463f-977e-0803d0d93873")]
            public class DefaultForThisDomainInfoClass : RepoItemInfo
            {
                /// <summary>
                /// DefaultForThisDomainInfoClass class constructor.
                /// </summary>
                public DefaultForThisDomainInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "DefaultForThisDomain", ".//section[#'float']//article/ul/li[3]//span[@innertext='Bank Holidays ']/?/?/strong[@innertext='Default for this domain']", 30000, null, "d01638b7-aad6-463f-977e-0803d0d93873")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("25c0a3df-c59e-4266-83bc-272911ffed69")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("25c0a3df-c59e-4266-83bc-272911ffed69");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("25c0a3df-c59e-4266-83bc-272911ffed69")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("25c0a3df-c59e-4266-83bc-272911ffed69", cropRect);
                }
            }

            /// <summary>
            /// The HttpsExt735OpcoCaasEdgevisIo944InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3d077a87-3ea7-4faf-91ab-000529de797e")]
            public class HttpsExt735OpcoCaasEdgevisIo944InfoClass : RepoItemInfo
            {
                /// <summary>
                /// HttpsExt735OpcoCaasEdgevisIo944InfoClass class constructor.
                /// </summary>
                public HttpsExt735OpcoCaasEdgevisIo944InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "HttpsExt735OpcoCaasEdgevisIo944", ".//section[#'float']//article/ul/li[10]/a[@href>'https://ext-735-opco.caas']", 30000, null, "3d077a87-3ea7-4faf-91ab-000529de797e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("ccdc674d-9c95-4645-bb6a-800b5565d56c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("ccdc674d-9c95-4645-bb6a-800b5565d56c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ccdc674d-9c95-4645-bb6a-800b5565d56c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ccdc674d-9c95-4645-bb6a-800b5565d56c", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9a60ef8-a539-4715-a337-85a448c239ae")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9a60ef8-a539-4715-a337-85a448c239ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FullWidthNgScope item.
            /// </summary>
            [RepositoryItem("23e12b43-add1-41ac-ba15-4286b8342e8c")]
            public virtual Ranorex.HeaderTag FullWidthNgScope
            {
                get
                {
                    return _fullwidthngscopeInfo.CreateAdapter<Ranorex.HeaderTag>(true);
                }
            }

            /// <summary>
            /// The FullWidthNgScope item info.
            /// </summary>
            [RepositoryItemInfo("23e12b43-add1-41ac-ba15-4286b8342e8c")]
            public virtual RepoItemInfo FullWidthNgScopeInfo
            {
                get
                {
                    return _fullwidthngscopeInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("90e78f95-d8dd-4d16-ab6c-0f5d9d77c28b")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The SCHEDULE item.
            /// </summary>
            [RepositoryItem("58eaa606-0c7b-4cf1-a77b-6e8179645aac")]
            public virtual Ranorex.SelectTag SCHEDULE
            {
                get
                {
                    return _scheduleInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SCHEDULE item info.
            /// </summary>
            [RepositoryItemInfo("58eaa606-0c7b-4cf1-a77b-6e8179645aac")]
            public virtual RepoItemInfo SCHEDULEInfo
            {
                get
                {
                    return _scheduleInfo;
                }
            }

            /// <summary>
            /// The PickYourAlarmSettings item.
            /// </summary>
            [RepositoryItem("59e41956-c6ea-4a0c-8f1f-c60b14bd26c8")]
            public virtual Ranorex.H1Tag PickYourAlarmSettings
            {
                get
                {
                    return _pickyouralarmsettingsInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The PickYourAlarmSettings item info.
            /// </summary>
            [RepositoryItemInfo("59e41956-c6ea-4a0c-8f1f-c60b14bd26c8")]
            public virtual RepoItemInfo PickYourAlarmSettingsInfo
            {
                get
                {
                    return _pickyouralarmsettingsInfo;
                }
            }

            /// <summary>
            /// The Account item.
            /// </summary>
            [RepositoryItem("c09551df-3b95-40e6-aa88-dd8bae88aec2")]
            public virtual Ranorex.SpanTag Account
            {
                get
                {
                    return _accountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account item info.
            /// </summary>
            [RepositoryItemInfo("c09551df-3b95-40e6-aa88-dd8bae88aec2")]
            public virtual RepoItemInfo AccountInfo
            {
                get
                {
                    return _accountInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("b4031387-8833-4efa-ade4-97b0c7f4b3ad")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("b4031387-8833-4efa-ade4-97b0c7f4b3ad")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("e46edd80-b215-4542-bb5a-fa434cc8c32f")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("e46edd80-b215-4542-bb5a-fa434cc8c32f")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Test item.
            /// </summary>
            [RepositoryItem("a1a2654c-6152-49ff-9e74-ce7b54aebf8b")]
            public virtual Ranorex.SpanTag Test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Test item info.
            /// </summary>
            [RepositoryItemInfo("a1a2654c-6152-49ff-9e74-ce7b54aebf8b")]
            public virtual RepoItemInfo TestInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The FindOutMoreAboutAlarmScheduling item.
            /// </summary>
            [RepositoryItem("bc16c320-b69e-4103-85e9-5476fb896510")]
            public virtual Ranorex.ATag FindOutMoreAboutAlarmScheduling
            {
                get
                {
                    return _findoutmoreaboutalarmschedulingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FindOutMoreAboutAlarmScheduling item info.
            /// </summary>
            [RepositoryItemInfo("bc16c320-b69e-4103-85e9-5476fb896510")]
            public virtual RepoItemInfo FindOutMoreAboutAlarmSchedulingInfo
            {
                get
                {
                    return _findoutmoreaboutalarmschedulingInfo;
                }
            }

            /// <summary>
            /// The ThursdayWorkingHours item.
            /// </summary>
            [RepositoryItem("bf3cc242-118b-4782-a062-cbcf0f0d2894")]
            public virtual Ranorex.SpanTag ThursdayWorkingHours
            {
                get
                {
                    return _thursdayworkinghoursInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ThursdayWorkingHours item info.
            /// </summary>
            [RepositoryItemInfo("bf3cc242-118b-4782-a062-cbcf0f0d2894")]
            public virtual RepoItemInfo ThursdayWorkingHoursInfo
            {
                get
                {
                    return _thursdayworkinghoursInfo;
                }
            }

            /// <summary>
            /// The AddDay item.
            /// </summary>
            [RepositoryItem("3ab2d50e-ee87-48fb-8264-e872e0a35672")]
            public virtual Ranorex.SelectTag AddDay
            {
                get
                {
                    return _adddayInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AddDay item info.
            /// </summary>
            [RepositoryItemInfo("3ab2d50e-ee87-48fb-8264-e872e0a35672")]
            public virtual RepoItemInfo AddDayInfo
            {
                get
                {
                    return _adddayInfo;
                }
            }

            /// <summary>
            /// The NgScope item.
            /// </summary>
            [RepositoryItem("77f69edd-8288-4cb8-b705-41129eb5713f")]
            public virtual Ranorex.DivTag NgScope
            {
                get
                {
                    return _ngscopeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgScope item info.
            /// </summary>
            [RepositoryItemInfo("77f69edd-8288-4cb8-b705-41129eb5713f")]
            public virtual RepoItemInfo NgScopeInfo
            {
                get
                {
                    return _ngscopeInfo;
                }
            }

            /// <summary>
            /// The AddTimeHours item.
            /// </summary>
            [RepositoryItem("20178f26-3265-4566-9a59-7c1d1f53125f")]
            public virtual Ranorex.SelectTag AddTimeHours
            {
                get
                {
                    return _addtimehoursInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AddTimeHours item info.
            /// </summary>
            [RepositoryItemInfo("20178f26-3265-4566-9a59-7c1d1f53125f")]
            public virtual RepoItemInfo AddTimeHoursInfo
            {
                get
                {
                    return _addtimehoursInfo;
                }
            }

            /// <summary>
            /// The AddAction item.
            /// </summary>
            [RepositoryItem("ffae465f-840e-49a9-b48d-6ff1d0a1e7eb")]
            public virtual Ranorex.SelectTag AddAction
            {
                get
                {
                    return _addactionInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AddAction item info.
            /// </summary>
            [RepositoryItemInfo("ffae465f-840e-49a9-b48d-6ff1d0a1e7eb")]
            public virtual RepoItemInfo AddActionInfo
            {
                get
                {
                    return _addactionInfo;
                }
            }

            /// <summary>
            /// The Form item.
            /// </summary>
            [RepositoryItem("1316e814-89ac-484e-85d1-ec38c3c1eeda")]
            public virtual Ranorex.FormTag Form
            {
                get
                {
                    return _formInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The Form item info.
            /// </summary>
            [RepositoryItemInfo("1316e814-89ac-484e-85d1-ec38c3c1eeda")]
            public virtual RepoItemInfo FormInfo
            {
                get
                {
                    return _formInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("b489380f-8232-408c-aa99-67657f2983dd")]
            public virtual Ranorex.ATag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("b489380f-8232-408c-aa99-67657f2983dd")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The SomeTdTag item.
            /// </summary>
            [RepositoryItem("7c6ec7aa-b898-49c5-8b17-8c4c455fb9bf")]
            public virtual Ranorex.TdTag SomeTdTag
            {
                get
                {
                    return _sometdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag item info.
            /// </summary>
            [RepositoryItemInfo("7c6ec7aa-b898-49c5-8b17-8c4c455fb9bf")]
            public virtual RepoItemInfo SomeTdTagInfo
            {
                get
                {
                    return _sometdtagInfo;
                }
            }

            /// <summary>
            /// The DeleteSchedule item.
            /// </summary>
            [RepositoryItem("9b858aea-7460-4efb-bf08-80249436dbfc")]
            public virtual Ranorex.ATag DeleteSchedule
            {
                get
                {
                    return _deletescheduleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DeleteSchedule item info.
            /// </summary>
            [RepositoryItemInfo("9b858aea-7460-4efb-bf08-80249436dbfc")]
            public virtual RepoItemInfo DeleteScheduleInfo
            {
                get
                {
                    return _deletescheduleInfo;
                }
            }

            /// <summary>
            /// The BodyTagTop item.
            /// </summary>
            [RepositoryItem("e2662629-bfc7-4dec-ac3a-2ee8f34794bd")]
            public virtual Ranorex.BodyTag BodyTagTop
            {
                get
                {
                    return _bodytagtopInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The BodyTagTop item info.
            /// </summary>
            [RepositoryItemInfo("e2662629-bfc7-4dec-ac3a-2ee8f34794bd")]
            public virtual RepoItemInfo BodyTagTopInfo
            {
                get
                {
                    return _bodytagtopInfo;
                }
            }

            /// <summary>
            /// The AddDay1 item.
            /// </summary>
            [RepositoryItem("be6aa740-6b69-4248-8617-a398475fba47")]
            public virtual Ranorex.SelectTag AddDay1
            {
                get
                {
                    return _addday1Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AddDay1 item info.
            /// </summary>
            [RepositoryItemInfo("be6aa740-6b69-4248-8617-a398475fba47")]
            public virtual RepoItemInfo AddDay1Info
            {
                get
                {
                    return _addday1Info;
                }
            }

            /// <summary>
            /// The SomeTdTag1 item.
            /// </summary>
            [RepositoryItem("63728c1c-ee87-426e-bac4-63d36c1d8c26")]
            public virtual Ranorex.TdTag SomeTdTag1
            {
                get
                {
                    return _sometdtag1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The SomeTdTag1 item info.
            /// </summary>
            [RepositoryItemInfo("63728c1c-ee87-426e-bac4-63d36c1d8c26")]
            public virtual RepoItemInfo SomeTdTag1Info
            {
                get
                {
                    return _sometdtag1Info;
                }
            }

            /// <summary>
            /// The Confirm item.
            /// </summary>
            [RepositoryItem("72ba7444-4873-47bd-97cb-4187b3268126")]
            public virtual Ranorex.ATag Confirm
            {
                get
                {
                    return _confirmInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Confirm item info.
            /// </summary>
            [RepositoryItemInfo("72ba7444-4873-47bd-97cb-4187b3268126")]
            public virtual RepoItemInfo ConfirmInfo
            {
                get
                {
                    return _confirmInfo;
                }
            }

            /// <summary>
            /// The AlarmScheduling item.
            /// </summary>
            [RepositoryItem("2f92af02-1ee3-428b-9cf4-6891c1f47c8b")]
            public virtual Ranorex.SpanTag AlarmScheduling
            {
                get
                {
                    return _alarmschedulingInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AlarmScheduling item info.
            /// </summary>
            [RepositoryItemInfo("2f92af02-1ee3-428b-9cf4-6891c1f47c8b")]
            public virtual RepoItemInfo AlarmSchedulingInfo
            {
                get
                {
                    return _alarmschedulingInfo;
                }
            }

            /// <summary>
            /// The ExceptionList item.
            /// </summary>
            [RepositoryItem("5e11aa18-727d-46f7-b1ac-e84a530232a6")]
            public virtual Ranorex.SpanTag ExceptionList
            {
                get
                {
                    return _exceptionlistInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ExceptionList item info.
            /// </summary>
            [RepositoryItemInfo("5e11aa18-727d-46f7-b1ac-e84a530232a6")]
            public virtual RepoItemInfo ExceptionListInfo
            {
                get
                {
                    return _exceptionlistInfo;
                }
            }

            /// <summary>
            /// The Test1 item.
            /// </summary>
            [RepositoryItem("05d0a20b-9ece-4d13-b173-692746dfd958")]
            public virtual Ranorex.SpanTag Test1
            {
                get
                {
                    return _test1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Test1 item info.
            /// </summary>
            [RepositoryItemInfo("05d0a20b-9ece-4d13-b173-692746dfd958")]
            public virtual RepoItemInfo Test1Info
            {
                get
                {
                    return _test1Info;
                }
            }

            /// <summary>
            /// The AddDate item.
            /// </summary>
            [RepositoryItem("5b3dcac7-6c22-444e-8a84-47d3e3c7ef8b")]
            public virtual Ranorex.InputTag AddDate
            {
                get
                {
                    return _adddateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AddDate item info.
            /// </summary>
            [RepositoryItemInfo("5b3dcac7-6c22-444e-8a84-47d3e3c7ef8b")]
            public virtual RepoItemInfo AddDateInfo
            {
                get
                {
                    return _adddateInfo;
                }
            }

            /// <summary>
            /// The ATagAdd item.
            /// </summary>
            [RepositoryItem("8616b60b-5ac2-40fb-9df6-5c4c25fb926a")]
            public virtual Ranorex.ATag ATagAdd
            {
                get
                {
                    return _atagaddInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagAdd item info.
            /// </summary>
            [RepositoryItemInfo("8616b60b-5ac2-40fb-9df6-5c4c25fb926a")]
            public virtual RepoItemInfo ATagAddInfo
            {
                get
                {
                    return _atagaddInfo;
                }
            }

            /// <summary>
            /// The EXCEPTIONS item.
            /// </summary>
            [RepositoryItem("758df2dc-ef7e-40b2-aadc-d2a7a22f220a")]
            public virtual Ranorex.SelectTag EXCEPTIONS
            {
                get
                {
                    return _exceptionsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The EXCEPTIONS item info.
            /// </summary>
            [RepositoryItemInfo("758df2dc-ef7e-40b2-aadc-d2a7a22f220a")]
            public virtual RepoItemInfo EXCEPTIONSInfo
            {
                get
                {
                    return _exceptionsInfo;
                }
            }

            /// <summary>
            /// The DefaultForThisDomain item.
            /// </summary>
            [RepositoryItem("d01638b7-aad6-463f-977e-0803d0d93873")]
            public virtual Ranorex.StrongTag DefaultForThisDomain
            {
                get
                {
                    return _defaultforthisdomainInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The DefaultForThisDomain item info.
            /// </summary>
            [RepositoryItemInfo("d01638b7-aad6-463f-977e-0803d0d93873")]
            public virtual DefaultForThisDomainInfoClass DefaultForThisDomainInfo
            {
                get
                {
                    return _defaultforthisdomainInfo;
                }
            }

            /// <summary>
            /// The HttpsExt735OpcoCaasEdgevisIo944 item.
            /// </summary>
            [RepositoryItem("3d077a87-3ea7-4faf-91ab-000529de797e")]
            public virtual Ranorex.ATag HttpsExt735OpcoCaasEdgevisIo944
            {
                get
                {
                    return _httpsext735opcocaasedgevisio944Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsExt735OpcoCaasEdgevisIo944 item info.
            /// </summary>
            [RepositoryItemInfo("3d077a87-3ea7-4faf-91ab-000529de797e")]
            public virtual HttpsExt735OpcoCaasEdgevisIo944InfoClass HttpsExt735OpcoCaasEdgevisIo944Info
            {
                get
                {
                    return _httpsext735opcocaasedgevisio944Info;
                }
            }

            /// <summary>
            /// The DefaultForThisDomain1 item.
            /// </summary>
            [RepositoryItem("04b583ba-4c91-41ae-8c11-8107ee34b9a8")]
            public virtual Ranorex.SpanTag DefaultForThisDomain1
            {
                get
                {
                    return _defaultforthisdomain1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DefaultForThisDomain1 item info.
            /// </summary>
            [RepositoryItemInfo("04b583ba-4c91-41ae-8c11-8107ee34b9a8")]
            public virtual RepoItemInfo DefaultForThisDomain1Info
            {
                get
                {
                    return _defaultforthisdomain1Info;
                }
            }

            /// <summary>
            /// The SelectAnExceptionList item.
            /// </summary>
            [RepositoryItem("4ff8a0f0-2bca-4c15-8dc8-8ec295dc0774")]
            public virtual Ranorex.H2Tag SelectAnExceptionList
            {
                get
                {
                    return _selectanexceptionlistInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The SelectAnExceptionList item info.
            /// </summary>
            [RepositoryItemInfo("4ff8a0f0-2bca-4c15-8dc8-8ec295dc0774")]
            public virtual RepoItemInfo SelectAnExceptionListInfo
            {
                get
                {
                    return _selectanexceptionlistInfo;
                }
            }

            /// <summary>
            /// The ContainerNgScope item.
            /// </summary>
            [RepositoryItem("e63a6a85-b91a-44c0-ba73-d86629360a66")]
            public virtual Ranorex.DivTag ContainerNgScope
            {
                get
                {
                    return _containerngscopeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContainerNgScope item info.
            /// </summary>
            [RepositoryItemInfo("e63a6a85-b91a-44c0-ba73-d86629360a66")]
            public virtual RepoItemInfo ContainerNgScopeInfo
            {
                get
                {
                    return _containerngscopeInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("c6e54d69-a969-4aca-87ca-3a86f823f66c")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("c6e54d69-a969-4aca-87ca-3a86f823f66c")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Test11 item.
            /// </summary>
            [RepositoryItem("6643b1d9-57e4-44c1-a983-369b97ed1df7")]
            public virtual Ranorex.SpanTag Test11
            {
                get
                {
                    return _test11Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Test11 item info.
            /// </summary>
            [RepositoryItemInfo("6643b1d9-57e4-44c1-a983-369b97ed1df7")]
            public virtual RepoItemInfo Test11Info
            {
                get
                {
                    return _test11Info;
                }
            }

            /// <summary>
            /// The FindOutMoreAboutAlarmScheduling1 item.
            /// </summary>
            [RepositoryItem("49e333cc-2606-43b1-9b28-e01d0d461c3f")]
            public virtual Ranorex.ATag FindOutMoreAboutAlarmScheduling1
            {
                get
                {
                    return _findoutmoreaboutalarmscheduling1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FindOutMoreAboutAlarmScheduling1 item info.
            /// </summary>
            [RepositoryItemInfo("49e333cc-2606-43b1-9b28-e01d0d461c3f")]
            public virtual RepoItemInfo FindOutMoreAboutAlarmScheduling1Info
            {
                get
                {
                    return _findoutmoreaboutalarmscheduling1Info;
                }
            }

            /// <summary>
            /// The ExceptionLists item.
            /// </summary>
            [RepositoryItem("15b0f15b-bd48-486c-9933-d92798e40b94")]
            public virtual Ranorex.StrongTag ExceptionLists
            {
                get
                {
                    return _exceptionlistsInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The ExceptionLists item info.
            /// </summary>
            [RepositoryItemInfo("15b0f15b-bd48-486c-9933-d92798e40b94")]
            public virtual RepoItemInfo ExceptionListsInfo
            {
                get
                {
                    return _exceptionlistsInfo;
                }
            }

            /// <summary>
            /// The ContentPage folder.
            /// </summary>
            [RepositoryFolder("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual VodafonePOCRepositoryFolders.ContentPageFolder ContentPage
            {
                get { return _contentpage; }
            }
        }

        /// <summary>
        /// The ContentPageFolder folder.
        /// </summary>
        [RepositoryFolder("373057e6-3382-4e46-815b-737e7abdbb6b")]
        public partial class ContentPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _choosedefaultforthisdomainInfo;
            RepoItemInfo _testInfo;
            RepoItemInfo _encodersettingsInfo;
            RepoItemInfo _nameInfo;
            RepoItemInfo _weeklyschedulesInfo;
            RepoItemInfo _exceptionlistsInfo;
            RepoItemInfo _smalltag7dayplannerslistingwhenalarInfo;

            /// <summary>
            /// Creates a new ContentPage  folder.
            /// </summary>
            public ContentPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentPage", ".//section[#'float']/div/div/div", parentFolder, 30000, null, false, "373057e6-3382-4e46-815b-737e7abdbb6b", "")
            {
                _choosedefaultforthisdomainInfo = new RepoItemInfo(this, "ChooseDefaultForThisDomain", "aside/ul/?/?/a[@innertext>'Choose default for this d']", 30000, null, "3aafab49-fb6a-4ed7-8831-7fcb38ebc523");
                _testInfo = new RepoItemInfo(this, "Test", "ul[1]/li[1]/a[@innertext='Test ']", 30000, null, "83065ac3-620b-48c5-a7e0-909a68083265");
                _encodersettingsInfo = new RepoItemInfo(this, "EncoderSettings", "ul[2]/?/?/a[@innertext='Encoder settings']", 30000, null, "078447a5-ed66-46f8-aa3e-51d4bde59158");
                _nameInfo = new RepoItemInfo(this, "Name", "article/ul/?/?/a/span[1]", 30000, null, "2707cfc6-deab-46a3-b4e2-5aa84bb938b2");
                _weeklyschedulesInfo = new RepoItemInfo(this, "WeeklySchedules", "article/ul//span[@innertext='Weekly schedules']", 30000, null, "e3ce8cc0-1be1-4d9f-b827-f36910b550ab");
                _exceptionlistsInfo = new RepoItemInfo(this, "ExceptionLists", "article/ul//span[@innertext='Exception lists']", 30000, null, "182bdc9c-d622-4c23-8f8a-5caa6b06eb9c");
                _smalltag7dayplannerslistingwhenalarInfo = new RepoItemInfo(this, "SmallTag7DayPlannersListingWhenAlar", "article/ul//small[@innertext>'7-day planners listing when']", 30000, null, "4fe48ed5-9cf3-43d4-a63b-9ea820d09b79");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("373057e6-3382-4e46-815b-737e7abdbb6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChooseDefaultForThisDomain item.
            /// </summary>
            [RepositoryItem("3aafab49-fb6a-4ed7-8831-7fcb38ebc523")]
            public virtual Ranorex.ATag ChooseDefaultForThisDomain
            {
                get
                {
                    return _choosedefaultforthisdomainInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ChooseDefaultForThisDomain item info.
            /// </summary>
            [RepositoryItemInfo("3aafab49-fb6a-4ed7-8831-7fcb38ebc523")]
            public virtual RepoItemInfo ChooseDefaultForThisDomainInfo
            {
                get
                {
                    return _choosedefaultforthisdomainInfo;
                }
            }

            /// <summary>
            /// The Test item.
            /// </summary>
            [RepositoryItem("83065ac3-620b-48c5-a7e0-909a68083265")]
            public virtual Ranorex.ATag Test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Test item info.
            /// </summary>
            [RepositoryItemInfo("83065ac3-620b-48c5-a7e0-909a68083265")]
            public virtual RepoItemInfo TestInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The EncoderSettings item.
            /// </summary>
            [RepositoryItem("078447a5-ed66-46f8-aa3e-51d4bde59158")]
            public virtual Ranorex.ATag EncoderSettings
            {
                get
                {
                    return _encodersettingsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EncoderSettings item info.
            /// </summary>
            [RepositoryItemInfo("078447a5-ed66-46f8-aa3e-51d4bde59158")]
            public virtual RepoItemInfo EncoderSettingsInfo
            {
                get
                {
                    return _encodersettingsInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("2707cfc6-deab-46a3-b4e2-5aa84bb938b2")]
            public virtual Ranorex.SpanTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("2707cfc6-deab-46a3-b4e2-5aa84bb938b2")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The WeeklySchedules item.
            /// </summary>
            [RepositoryItem("e3ce8cc0-1be1-4d9f-b827-f36910b550ab")]
            public virtual Ranorex.SpanTag WeeklySchedules
            {
                get
                {
                    return _weeklyschedulesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The WeeklySchedules item info.
            /// </summary>
            [RepositoryItemInfo("e3ce8cc0-1be1-4d9f-b827-f36910b550ab")]
            public virtual RepoItemInfo WeeklySchedulesInfo
            {
                get
                {
                    return _weeklyschedulesInfo;
                }
            }

            /// <summary>
            /// The ExceptionLists item.
            /// </summary>
            [RepositoryItem("182bdc9c-d622-4c23-8f8a-5caa6b06eb9c")]
            public virtual Ranorex.SpanTag ExceptionLists
            {
                get
                {
                    return _exceptionlistsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ExceptionLists item info.
            /// </summary>
            [RepositoryItemInfo("182bdc9c-d622-4c23-8f8a-5caa6b06eb9c")]
            public virtual RepoItemInfo ExceptionListsInfo
            {
                get
                {
                    return _exceptionlistsInfo;
                }
            }

            /// <summary>
            /// The SmallTag7DayPlannersListingWhenAlar item.
            /// </summary>
            [RepositoryItem("4fe48ed5-9cf3-43d4-a63b-9ea820d09b79")]
            public virtual Ranorex.SmallTag SmallTag7DayPlannersListingWhenAlar
            {
                get
                {
                    return _smalltag7dayplannerslistingwhenalarInfo.CreateAdapter<Ranorex.SmallTag>(true);
                }
            }

            /// <summary>
            /// The SmallTag7DayPlannersListingWhenAlar item info.
            /// </summary>
            [RepositoryItemInfo("4fe48ed5-9cf3-43d4-a63b-9ea820d09b79")]
            public virtual RepoItemInfo SmallTag7DayPlannersListingWhenAlarInfo
            {
                get
                {
                    return _smalltag7dayplannerslistingwhenalarInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
        public partial class MicrosoftEdgeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchorenterwebaddressInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _mnavswipescrollerInfo;

            /// <summary>
            /// Creates a new MicrosoftEdge  folder.
            /// </summary>
            public MicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftEdge", "/winapp[@packagename='Microsoft.MicrosoftEdge']", parentFolder, 30000, null, true, "763b2766-dcca-4ff9-9878-dc48c2a3f4fe", "")
            {
                _searchorenterwebaddressInfo = new RepoItemInfo(this, "SearchOrEnterWebAddress", "?/?/text[@name>'Search or enter web addre']", 30000, null, "30c0962c-9ff4-48d4-b562-78ecf6f7d11b");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "list[@automationid='TabsList']//button[@automationid='AllInputCloseButton']/text[@name='']", 30000, null, "4e49b5cf-1978-4d31-88e3-601ad15bb00d");
                _mnavswipescrollerInfo = new RepoItemInfo(this, "MNavSwipeScroller", "?/?/container[@automationid='m_navSwipeScroller']", 30000, null, "e56c2c67-5441-417a-bc3f-a17016014e00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("763b2766-dcca-4ff9-9878-dc48c2a3f4fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchOrEnterWebAddress item.
            /// </summary>
            [RepositoryItem("30c0962c-9ff4-48d4-b562-78ecf6f7d11b")]
            public virtual Ranorex.Text SearchOrEnterWebAddress
            {
                get
                {
                    return _searchorenterwebaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SearchOrEnterWebAddress item info.
            /// </summary>
            [RepositoryItemInfo("30c0962c-9ff4-48d4-b562-78ecf6f7d11b")]
            public virtual RepoItemInfo SearchOrEnterWebAddressInfo
            {
                get
                {
                    return _searchorenterwebaddressInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("4e49b5cf-1978-4d31-88e3-601ad15bb00d")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("4e49b5cf-1978-4d31-88e3-601ad15bb00d")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The MNavSwipeScroller item.
            /// </summary>
            [RepositoryItem("e56c2c67-5441-417a-bc3f-a17016014e00")]
            public virtual Ranorex.Container MNavSwipeScroller
            {
                get
                {
                    return _mnavswipescrollerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The MNavSwipeScroller item info.
            /// </summary>
            [RepositoryItemInfo("e56c2c67-5441-417a-bc3f-a17016014e00")]
            public virtual RepoItemInfo MNavSwipeScrollerInfo
            {
                get
                {
                    return _mnavswipescrollerInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;
            RepoItemInfo _acceptInfo;
            RepoItemInfo _septemberInfo;
            RepoItemInfo _client1Info;

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "de3b3b23-69e2-4e5a-92fe-7fd1894fa041", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "listitem", 30000, null, "a333b0d6-92ea-41fa-9477-0e56def63af8");
                _acceptInfo = new RepoItemInfo(this, "Accept", "?/?/button[@accessiblename='Accept']", 30000, null, "50bba6b2-df7b-4e8c-bf5d-f9b65a5e41ee");
                _septemberInfo = new RepoItemInfo(this, "September", "?/?/list[@accessiblename='Month']/listitem[@accessiblename='September']", 30000, null, "dec91d1b-47c6-41ab-9fa2-1a79620817c5");
                _client1Info = new RepoItemInfo(this, "Client1", "?/?/button", 30000, null, "5e3fe622-8ea6-46a2-b72f-15fea39c18ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de3b3b23-69e2-4e5a-92fe-7fd1894fa041")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("a333b0d6-92ea-41fa-9477-0e56def63af8")]
            public virtual Ranorex.ListItem Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("a333b0d6-92ea-41fa-9477-0e56def63af8")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The Accept item.
            /// </summary>
            [RepositoryItem("50bba6b2-df7b-4e8c-bf5d-f9b65a5e41ee")]
            public virtual Ranorex.Button Accept
            {
                get
                {
                    return _acceptInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Accept item info.
            /// </summary>
            [RepositoryItemInfo("50bba6b2-df7b-4e8c-bf5d-f9b65a5e41ee")]
            public virtual RepoItemInfo AcceptInfo
            {
                get
                {
                    return _acceptInfo;
                }
            }

            /// <summary>
            /// The September item.
            /// </summary>
            [RepositoryItem("dec91d1b-47c6-41ab-9fa2-1a79620817c5")]
            public virtual Ranorex.ListItem September
            {
                get
                {
                    return _septemberInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The September item info.
            /// </summary>
            [RepositoryItemInfo("dec91d1b-47c6-41ab-9fa2-1a79620817c5")]
            public virtual RepoItemInfo SeptemberInfo
            {
                get
                {
                    return _septemberInfo;
                }
            }

            /// <summary>
            /// The Client1 item.
            /// </summary>
            [RepositoryItem("5e3fe622-8ea6-46a2-b72f-15fea39c18ef")]
            public virtual Ranorex.Button Client1
            {
                get
                {
                    return _client1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Client1 item info.
            /// </summary>
            [RepositoryItemInfo("5e3fe622-8ea6-46a2-b72f-15fea39c18ef")]
            public virtual RepoItemInfo Client1Info
            {
                get
                {
                    return _client1Info;
                }
            }
        }

        /// <summary>
        /// The CharacterEncodingRStudioSupportAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
        public partial class CharacterEncodingRStudioSupportAppFolder : RepoGenBaseFolder
        {
            VodafonePOCRepositoryFolders.SomeMainTagFolder _somemaintag;
            RepoItemInfo _communityenabledInfo;

            /// <summary>
            /// Creates a new CharacterEncodingRStudioSupport  folder.
            /// </summary>
            public CharacterEncodingRStudioSupportAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CharacterEncodingRStudioSupport", "/dom[@domain='support.rstudio.com']", parentFolder, 30000, null, false, "3ff4ab92-369d-4ee9-a944-6c8be07d020c", "")
            {
                _somemaintag = new VodafonePOCRepositoryFolders.SomeMainTagFolder(this);
                _communityenabledInfo = new RepoItemInfo(this, "CommunityEnabled", "body", 30000, null, "158004ef-e852-4bbc-a50f-d8d82abb8705");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ff4ab92-369d-4ee9-a944-6c8be07d020c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CommunityEnabled item.
            /// </summary>
            [RepositoryItem("158004ef-e852-4bbc-a50f-d8d82abb8705")]
            public virtual Ranorex.BodyTag CommunityEnabled
            {
                get
                {
                    return _communityenabledInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The CommunityEnabled item info.
            /// </summary>
            [RepositoryItemInfo("158004ef-e852-4bbc-a50f-d8d82abb8705")]
            public virtual RepoItemInfo CommunityEnabledInfo
            {
                get
                {
                    return _communityenabledInfo;
                }
            }

            /// <summary>
            /// The SomeMainTag folder.
            /// </summary>
            [RepositoryFolder("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual VodafonePOCRepositoryFolders.SomeMainTagFolder SomeMainTag
            {
                get { return _somemaintag; }
            }
        }

        /// <summary>
        /// The SomeMainTagFolder folder.
        /// </summary>
        [RepositoryFolder("22185695-afd3-4091-874d-ae9fa0d5ca60")]
        public partial class SomeMainTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ifyoudontsetadefaultencodingfileInfo;
            RepoItemInfo _ifyoufrequentlyusethecharactersetInfo;
            RepoItemInfo _articlebodyInfo;

            /// <summary>
            /// Creates a new SomeMainTag  folder.
            /// </summary>
            public SomeMainTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeMainTag", "?/?/main", parentFolder, 30000, null, false, "22185695-afd3-4091-874d-ae9fa0d5ca60", "")
            {
                _ifyoudontsetadefaultencodingfileInfo = new RepoItemInfo(this, "IfYouDontSetADefaultEncodingFile", "?/?/article/?/?/p[@innertext>'If you don''t set a default']", 30000, null, "2819a39d-14d5-4e9c-9e7b-8f810d0a9a26");
                _ifyoufrequentlyusethecharactersetInfo = new RepoItemInfo(this, "IfYouFrequentlyUseTheCharacterSet", "?/?/article/?/?/p[@innertext>'If you frequently use the']", 30000, null, "adbd7a80-cb69-4357-9c1f-3c3101c12392");
                _articlebodyInfo = new RepoItemInfo(this, "ArticleBody", "?/?/article/div[1]", 30000, null, "2d9a0b5c-bac9-44e0-ae84-c2becd94695a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual Ranorex.MainTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MainTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("22185695-afd3-4091-874d-ae9fa0d5ca60")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IfYouDontSetADefaultEncodingFile item.
            /// </summary>
            [RepositoryItem("2819a39d-14d5-4e9c-9e7b-8f810d0a9a26")]
            public virtual Ranorex.PTag IfYouDontSetADefaultEncodingFile
            {
                get
                {
                    return _ifyoudontsetadefaultencodingfileInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IfYouDontSetADefaultEncodingFile item info.
            /// </summary>
            [RepositoryItemInfo("2819a39d-14d5-4e9c-9e7b-8f810d0a9a26")]
            public virtual RepoItemInfo IfYouDontSetADefaultEncodingFileInfo
            {
                get
                {
                    return _ifyoudontsetadefaultencodingfileInfo;
                }
            }

            /// <summary>
            /// The IfYouFrequentlyUseTheCharacterSet item.
            /// </summary>
            [RepositoryItem("adbd7a80-cb69-4357-9c1f-3c3101c12392")]
            public virtual Ranorex.PTag IfYouFrequentlyUseTheCharacterSet
            {
                get
                {
                    return _ifyoufrequentlyusethecharactersetInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IfYouFrequentlyUseTheCharacterSet item info.
            /// </summary>
            [RepositoryItemInfo("adbd7a80-cb69-4357-9c1f-3c3101c12392")]
            public virtual RepoItemInfo IfYouFrequentlyUseTheCharacterSetInfo
            {
                get
                {
                    return _ifyoufrequentlyusethecharactersetInfo;
                }
            }

            /// <summary>
            /// The ArticleBody item.
            /// </summary>
            [RepositoryItem("2d9a0b5c-bac9-44e0-ae84-c2becd94695a")]
            public virtual Ranorex.DivTag ArticleBody
            {
                get
                {
                    return _articlebodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ArticleBody item info.
            /// </summary>
            [RepositoryItemInfo("2d9a0b5c-bac9-44e0-ae84-c2becd94695a")]
            public virtual RepoItemInfo ArticleBodyInfo
            {
                get
                {
                    return _articlebodyInfo;
                }
            }
        }

        /// <summary>
        /// The Ranorex93GoogleSearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("739c31f1-4f9e-425e-b95d-733894c2348f")]
        public partial class Ranorex93GoogleSearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somelitagInfo;

            /// <summary>
            /// Creates a new Ranorex93GoogleSearch  folder.
            /// </summary>
            public Ranorex93GoogleSearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Ranorex93GoogleSearch", "/dom[@domain='www.google.co.uk']", parentFolder, 30000, null, false, "739c31f1-4f9e-425e-b95d-733894c2348f", "")
            {
                _somelitagInfo = new RepoItemInfo(this, "SomeLiTag", ".//div[#'tads']//ul/li[2]", 30000, null, "ef6c0e90-c33c-4cf7-bab2-e787e8aa4c1f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("739c31f1-4f9e-425e-b95d-733894c2348f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("739c31f1-4f9e-425e-b95d-733894c2348f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeLiTag item.
            /// </summary>
            [RepositoryItem("ef6c0e90-c33c-4cf7-bab2-e787e8aa4c1f")]
            public virtual Ranorex.LiTag SomeLiTag
            {
                get
                {
                    return _somelitagInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The SomeLiTag item info.
            /// </summary>
            [RepositoryItemInfo("ef6c0e90-c33c-4cf7-bab2-e787e8aa4c1f")]
            public virtual RepoItemInfo SomeLiTagInfo
            {
                get
                {
                    return _somelitagInfo;
                }
            }
        }

        /// <summary>
        /// The MyhrtoolkitHRSoftwareAsAServiceAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f1caf70-70ae-4b26-86cb-dfa2261cdeec")]
        public partial class MyhrtoolkitHRSoftwareAsAServiceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localeInfo;

            /// <summary>
            /// Creates a new MyhrtoolkitHRSoftwareAsAService  folder.
            /// </summary>
            public MyhrtoolkitHRSoftwareAsAServiceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyhrtoolkitHRSoftwareAsAService", "/dom[@domain='app.myhrtoolkit.com']", parentFolder, 30000, null, false, "9f1caf70-70ae-4b26-86cb-dfa2261cdeec", "")
            {
                _localeInfo = new RepoItemInfo(this, "Locale", ".//table[#'site-wrapper']/tbody//div", 30000, null, "e985938a-7510-4fe3-81d8-f84f394f33b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f1caf70-70ae-4b26-86cb-dfa2261cdeec")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f1caf70-70ae-4b26-86cb-dfa2261cdeec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Locale item.
            /// </summary>
            [RepositoryItem("e985938a-7510-4fe3-81d8-f84f394f33b3")]
            public virtual Ranorex.DivTag Locale
            {
                get
                {
                    return _localeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Locale item info.
            /// </summary>
            [RepositoryItemInfo("e985938a-7510-4fe3-81d8-f84f394f33b3")]
            public virtual RepoItemInfo LocaleInfo
            {
                get
                {
                    return _localeInfo;
                }
            }
        }

        /// <summary>
        /// The GTBoardAgileBoardJiraAppFolder folder.
        /// </summary>
        [RepositoryFolder("654275ce-97aa-416e-803a-bc6f7cbb9ab5")]
        public partial class GTBoardAgileBoardJiraAppFolder : RepoGenBaseFolder
        {
            VodafonePOCRepositoryFolders.GhxColumnsFolder _ghxcolumns;
            VodafonePOCRepositoryFolders.DrnsbFScImYgaFFolder _drnsbfscimygaf;

            /// <summary>
            /// Creates a new GTBoardAgileBoardJira  folder.
            /// </summary>
            public GTBoardAgileBoardJiraAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GTBoardAgileBoardJira", "/dom[@domain='digitalbarriers.atlassian.net']", parentFolder, 30000, null, false, "654275ce-97aa-416e-803a-bc6f7cbb9ab5", "")
            {
                _ghxcolumns = new VodafonePOCRepositoryFolders.GhxColumnsFolder(this);
                _drnsbfscimygaf = new VodafonePOCRepositoryFolders.DrnsbFScImYgaFFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("654275ce-97aa-416e-803a-bc6f7cbb9ab5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("654275ce-97aa-416e-803a-bc6f7cbb9ab5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GhxColumns folder.
            /// </summary>
            [RepositoryFolder("96db1f89-6c5b-48e6-a223-338f8c3abbe1")]
            public virtual VodafonePOCRepositoryFolders.GhxColumnsFolder GhxColumns
            {
                get { return _ghxcolumns; }
            }

            /// <summary>
            /// The DrnsbFScImYgaF folder.
            /// </summary>
            [RepositoryFolder("2471c46a-98b5-426d-ad44-55f0b407acc2")]
            public virtual VodafonePOCRepositoryFolders.DrnsbFScImYgaFFolder DrnsbFScImYgaF
            {
                get { return _drnsbfscimygaf; }
            }
        }

        /// <summary>
        /// The GhxColumnsFolder folder.
        /// </summary>
        [RepositoryFolder("96db1f89-6c5b-48e6-a223-338f8c3abbe1")]
        public partial class GhxColumnsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pocdesignprojectstructureandtestInfo;
            RepoItemInfo _ghxstatfieldsInfo;
            RepoItemInfo _ghxcolumnghxnarrowcarduisortableInfo;
            RepoItemInfo _ghxstatfields1Info;
            RepoItemInfo _ghxsubtaskgroupuisortableInfo;

            /// <summary>
            /// Creates a new GhxColumns  folder.
            /// </summary>
            public GhxColumnsFolder(RepoGenBaseFolder parentFolder) :
                    base("GhxColumns", ".//div[#'ghx-pool']/div[2]/ul", parentFolder, 30000, null, false, "96db1f89-6c5b-48e6-a223-338f8c3abbe1", "")
            {
                _pocdesignprojectstructureandtestInfo = new RepoItemInfo(this, "POCDesignProjectStructureAndTest", "li[3]//section[@innertext>'POC - Design Project Structure']", 30000, null, "c748e720-db3a-4561-890a-39b15f8ada01");
                _ghxstatfieldsInfo = new RepoItemInfo(this, "GhxStatFields", "li[3]/div/div[2]/div[2]/div/section[2]", 30000, null, "0ded0bbc-811d-4453-ad69-fd014766c72b");
                _ghxcolumnghxnarrowcarduisortableInfo = new RepoItemInfo(this, "GhxColumnGhxNarrowCardUiSortable", "li[4]", 30000, null, "9cebfdb5-3603-46d4-a997-d4bc748380e8");
                _ghxstatfields1Info = new RepoItemInfo(this, "GhxStatFields1", "li[1]/div/div/section[2]", 30000, null, "288eb21d-1ec7-4278-a983-2cecd6072d8b");
                _ghxsubtaskgroupuisortableInfo = new RepoItemInfo(this, "GhxSubtaskGroupUiSortable", "li[3]/div/div[2]/div[2]", 30000, null, "23c060bc-e6bf-4808-a7fb-07a375e08a6c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("96db1f89-6c5b-48e6-a223-338f8c3abbe1")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96db1f89-6c5b-48e6-a223-338f8c3abbe1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The POCDesignProjectStructureAndTest item.
            /// </summary>
            [RepositoryItem("c748e720-db3a-4561-890a-39b15f8ada01")]
            public virtual Ranorex.SectionTag POCDesignProjectStructureAndTest
            {
                get
                {
                    return _pocdesignprojectstructureandtestInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The POCDesignProjectStructureAndTest item info.
            /// </summary>
            [RepositoryItemInfo("c748e720-db3a-4561-890a-39b15f8ada01")]
            public virtual RepoItemInfo POCDesignProjectStructureAndTestInfo
            {
                get
                {
                    return _pocdesignprojectstructureandtestInfo;
                }
            }

            /// <summary>
            /// The GhxStatFields item.
            /// </summary>
            [RepositoryItem("0ded0bbc-811d-4453-ad69-fd014766c72b")]
            public virtual Ranorex.SectionTag GhxStatFields
            {
                get
                {
                    return _ghxstatfieldsInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The GhxStatFields item info.
            /// </summary>
            [RepositoryItemInfo("0ded0bbc-811d-4453-ad69-fd014766c72b")]
            public virtual RepoItemInfo GhxStatFieldsInfo
            {
                get
                {
                    return _ghxstatfieldsInfo;
                }
            }

            /// <summary>
            /// The GhxColumnGhxNarrowCardUiSortable item.
            /// </summary>
            [RepositoryItem("9cebfdb5-3603-46d4-a997-d4bc748380e8")]
            public virtual Ranorex.LiTag GhxColumnGhxNarrowCardUiSortable
            {
                get
                {
                    return _ghxcolumnghxnarrowcarduisortableInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The GhxColumnGhxNarrowCardUiSortable item info.
            /// </summary>
            [RepositoryItemInfo("9cebfdb5-3603-46d4-a997-d4bc748380e8")]
            public virtual RepoItemInfo GhxColumnGhxNarrowCardUiSortableInfo
            {
                get
                {
                    return _ghxcolumnghxnarrowcarduisortableInfo;
                }
            }

            /// <summary>
            /// The GhxStatFields1 item.
            /// </summary>
            [RepositoryItem("288eb21d-1ec7-4278-a983-2cecd6072d8b")]
            public virtual Ranorex.SectionTag GhxStatFields1
            {
                get
                {
                    return _ghxstatfields1Info.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The GhxStatFields1 item info.
            /// </summary>
            [RepositoryItemInfo("288eb21d-1ec7-4278-a983-2cecd6072d8b")]
            public virtual RepoItemInfo GhxStatFields1Info
            {
                get
                {
                    return _ghxstatfields1Info;
                }
            }

            /// <summary>
            /// The GhxSubtaskGroupUiSortable item.
            /// </summary>
            [RepositoryItem("23c060bc-e6bf-4808-a7fb-07a375e08a6c")]
            public virtual Ranorex.DivTag GhxSubtaskGroupUiSortable
            {
                get
                {
                    return _ghxsubtaskgroupuisortableInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GhxSubtaskGroupUiSortable item info.
            /// </summary>
            [RepositoryItemInfo("23c060bc-e6bf-4808-a7fb-07a375e08a6c")]
            public virtual RepoItemInfo GhxSubtaskGroupUiSortableInfo
            {
                get
                {
                    return _ghxsubtaskgroupuisortableInfo;
                }
            }
        }

        /// <summary>
        /// The DrnsbFScImYgaFFolder folder.
        /// </summary>
        [RepositoryFolder("2471c46a-98b5-426d-ad44-55f0b407acc2")]
        public partial class DrnsbFScImYgaFFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fhxbetscbyzvruscjlbbkxytvypInfo;
            RepoItemInfo _divtagbwrInfo;
            RepoItemInfo _fnaaeiscckixcInfo;

            /// <summary>
            /// Creates a new DrnsbFScImYgaF  folder.
            /// </summary>
            public DrnsbFScImYgaFFolder(RepoGenBaseFolder parentFolder) :
                    base("DrnsbFScImYgaF", ".//div[#'helpPanelContainer']/div/div[1]/div[3]/div[1]", parentFolder, 30000, null, false, "2471c46a-98b5-426d-ad44-55f0b407acc2", "")
            {
                _fhxbetscbyzvruscjlbbkxytvypInfo = new RepoItemInfo(this, "FhXBEtScBYzVrUScJlBbkxYTvYP", ".//table/tbody/tr[3]/td[2]/?/?/div", 30000, null, "db779df2-dc77-495d-a5df-8399048f3b7e");
                _divtagbwrInfo = new RepoItemInfo(this, "DivTagBWR", ".//table/tbody/tr[3]/td[3]/div[@innertext='BWR']", 30000, null, "b0dea96f-99e2-455b-898d-0bad98f65139");
                _fnaaeiscckixcInfo = new RepoItemInfo(this, "FNAaeiScCkixc", "div/div[2]/?/?/table/tbody/tr[1]/td[5]/div/div/div/div", 30000, null, "f0112a7a-d205-4730-9aba-6de19c5a02e2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2471c46a-98b5-426d-ad44-55f0b407acc2")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2471c46a-98b5-426d-ad44-55f0b407acc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FhXBEtScBYzVrUScJlBbkxYTvYP item.
            /// </summary>
            [RepositoryItem("db779df2-dc77-495d-a5df-8399048f3b7e")]
            public virtual Ranorex.DivTag FhXBEtScBYzVrUScJlBbkxYTvYP
            {
                get
                {
                    return _fhxbetscbyzvruscjlbbkxytvypInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FhXBEtScBYzVrUScJlBbkxYTvYP item info.
            /// </summary>
            [RepositoryItemInfo("db779df2-dc77-495d-a5df-8399048f3b7e")]
            public virtual RepoItemInfo FhXBEtScBYzVrUScJlBbkxYTvYPInfo
            {
                get
                {
                    return _fhxbetscbyzvruscjlbbkxytvypInfo;
                }
            }

            /// <summary>
            /// The DivTagBWR item.
            /// </summary>
            [RepositoryItem("b0dea96f-99e2-455b-898d-0bad98f65139")]
            public virtual Ranorex.DivTag DivTagBWR
            {
                get
                {
                    return _divtagbwrInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagBWR item info.
            /// </summary>
            [RepositoryItemInfo("b0dea96f-99e2-455b-898d-0bad98f65139")]
            public virtual RepoItemInfo DivTagBWRInfo
            {
                get
                {
                    return _divtagbwrInfo;
                }
            }

            /// <summary>
            /// The FNAaeiScCkixc item.
            /// </summary>
            [RepositoryItem("f0112a7a-d205-4730-9aba-6de19c5a02e2")]
            public virtual Ranorex.DivTag FNAaeiScCkixc
            {
                get
                {
                    return _fnaaeiscckixcInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FNAaeiScCkixc item info.
            /// </summary>
            [RepositoryItemInfo("f0112a7a-d205-4730-9aba-6de19c5a02e2")]
            public virtual RepoItemInfo FNAaeiScCkixcInfo
            {
                get
                {
                    return _fnaaeiscckixcInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("71bcaed3-06c6-4394-8cef-a16b6b1b952d")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "71bcaed3-06c6-4394-8cef-a16b6b1b952d", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "0b766076-d8be-4a36-80ff-e36370ddae0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71bcaed3-06c6-4394-8cef-a16b6b1b952d")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71bcaed3-06c6-4394-8cef-a16b6b1b952d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("0b766076-d8be-4a36-80ff-e36370ddae0a")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("0b766076-d8be-4a36-80ff-e36370ddae0a")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
